# Generated by Django 3.1.7 on 2021-04-22 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.SlugField(max_length=24, primary_key=True, serialize=False, verbose_name='ObjectID')),
                ('ref', models.SlugField(max_length=34, verbose_name='Ref')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('file_folder', models.FileField(default=None, max_length=254, null=True, upload_to='', verbose_name='Путь до папки с файлами')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='company.collection')),
                ('roles', models.ManyToManyField(related_name='docs', to='company.Role')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('text', models.TextField(null=True, verbose_name='Сообщение')),
                ('kind', models.IntegerField(verbose_name='Тип запроса')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Исполнено')),
                ('solved_at', models.DateTimeField(verbose_name='Дата исполнения')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_files', to='document.document')),
            ],
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('ref', 'collection'), name='unique_ref_collection'),
        ),
    ]
