# Generated by Django 3.1.7 on 2021-03-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongodb_id', models.CharField(max_length=25, verbose_name='ObjectID')),
                ('documet_ref', models.CharField(max_length=25, verbose_name='Ref')),
                ('saved', models.BooleanField(default=False, verbose_name='Сохранен')),
                ('file_path', models.FileField(default=None, max_length=254, null=True, upload_to='', verbose_name='Название')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='Заявка создана')),
                ('saved_file_date', models.DateTimeField(verbose_name='Файл сохранен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documentfile',
            constraint=models.UniqueConstraint(fields=('company', 'documet_ref'), name='unique_company_document'),
        ),
    ]
