# Generated by Django 3.1.7 on 2021-05-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_folder',
            field=models.CharField(default=None, max_length=254, null=True, verbose_name='Путь до папки с файлами'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ref',
            field=models.SlugField(max_length=36, verbose_name='Ref'),
        ),
    ]
