# Generated by Django 3.1.7 on 2021-03-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cabinet', '0005_auto_20210318_1008'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongodb_id', models.SlugField(max_length=25, verbose_name='ObjectID')),
                ('documet_ref', models.SlugField(max_length=25, verbose_name='Ref')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='documentfile',
            name='unique_company_document',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='documet_ref',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='mongodb_id',
        ),
        migrations.AddField(
            model_name='documentpermissions',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company'),
        ),
        migrations.AddField(
            model_name='documentpermissions',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentfile'),
        ),
        migrations.AddField(
            model_name='documentpermissions',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddConstraint(
            model_name='documentpermissions',
            constraint=models.UniqueConstraint(fields=('company', 'documet_ref'), name='unique_company_document'),
        ),
    ]
