# Generated by Django 3.1.7 on 2021-03-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210318_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpermissions',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentfile'),
        ),
    ]
