# Generated by Django 3.1.7 on 2021-05-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210507_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_folder',
            field=models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Путь до папки с файлами'),
        ),
    ]
