# Generated by Django 3.1.7 on 2021-03-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210318_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpermissions',
            name='documet_ref',
            field=models.SlugField(max_length=37, verbose_name='Ref'),
        ),
    ]
