# Generated by Django 3.1.7 on 2021-05-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20210507_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_folder',
            field=models.CharField(blank=True, default='', max_length=1023, null=True, verbose_name='Путь до папки с файлами'),
        ),
        migrations.AlterField(
            model_name='requestdoc',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
    ]
