# Generated by Django 3.1.7 on 2021-05-31 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0005_auto_20210531_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdoc',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_list', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestdoc',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_list', to='document.document'),
        ),
    ]
