# Generated by Django 3.1.6 on 2021-03-07 13:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название')),
                ('city', models.CharField(max_length=254, verbose_name='Город')),
                ('address', models.CharField(max_length=254, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('mongodb_collection', models.CharField(max_length=254, verbose_name='collection')),
                ('public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('secret_key', models.CharField(max_length=254, verbose_name='Ключ доступа')),
                ('password', models.CharField(max_length=254, verbose_name='Пароль')),
                ('users', models.ManyToManyField(to='cabinet.Account')),
            ],
        ),
    ]
