# Generated by Django 3.1.7 on 2021-03-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='users',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('companies', models.ManyToManyField(to='cabinet.Company')),
                ('group',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='auth.group')),
            ],
        ),
    ]
