# Generated by Django 3.1.7 on 2021-03-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_auto_20210318_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='cabinet.company'),
        ),
    ]
