# Generated by Django 3.1.7 on 2021-05-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='schema',
            field=models.JSONField(default=dict, verbose_name='Схема'),
        ),
    ]
