# Generated by Django 3.1.7 on 2021-06-01 18:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210506_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='url_name',
            field=models.CharField(default=django.utils.timezone.now,
                                   max_length=254,
                                   validators=[
                                       django.core.validators.RegexValidator(
                                           '^[a-zA-Z0-9а-яА-Я_-]+\\Z')
                                   ],
                                   verbose_name='URL название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True,
                                   max_length=12,
                                   null=True,
                                   verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True,
                                   max_length=12,
                                   null=True,
                                   verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='company',
            name='ogrp',
            field=models.CharField(blank=True,
                                   max_length=15,
                                   null=True,
                                   verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='company',
            name='okpo',
            field=models.CharField(blank=True,
                                   max_length=12,
                                   null=True,
                                   verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='company',
            name='url_name',
            field=models.CharField(default=django.utils.timezone.now,
                                   max_length=254,
                                   validators=[
                                       django.core.validators.RegexValidator(
                                           '^[a-zA-Z0-9а-яА-Я_-]+\\Z')
                                   ],
                                   verbose_name='URL название'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('url_name', 'company'),
                                               name='unique_system_name'),
        ),
    ]
