# Generated by Django 3.1.7 on 2021-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210601_1808'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_system_name',
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('url_name', 'company'), name='unique_system_name'),
        ),
    ]
