# Generated by Django 3.1.7 on 2021-06-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210601_1809'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_system_name',
        ),
    ]
